name: hits-recsys
channels:
  - pytorch
  - fastai
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - fastai>=2.7.14
  - pandas>=1.0.0
  - fastapi
  - fastprogress>=0.2.4
  - pytorch>=2.0.0
  - fastdownload
  - uvicorn