# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/hits-recsys',
                'doc_host': 'https://Ssslakter.github.io',
                'git_url': 'https://github.com/Ssslakter/hits-recsys',
                'lib_path': 'hits_recsys'},
  'syms': { 'hits_recsys.collab': { 'hits_recsys.collab.CollabUserBased': ('collab.html#collabuserbased', 'hits_recsys/collab.py'),
                                    'hits_recsys.collab.CollabUserBased.__init__': ( 'collab.html#collabuserbased.__init__',
                                                                                     'hits_recsys/collab.py'),
                                    'hits_recsys.collab.CollabUserBased.predict': ( 'collab.html#collabuserbased.predict',
                                                                                    'hits_recsys/collab.py'),
                                    'hits_recsys.collab.CollabUserBased.recommend': ( 'collab.html#collabuserbased.recommend',
                                                                                      'hits_recsys/collab.py')}}}
