name: Release project
permissions:
  contents: write
  pages: write

on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
    - uses: fastai/workflows/nbdev-ci@master
      with: 
        version: 3.11
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: model
        path: ./models/collab

  push_to_registry:
    needs: test
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - 
        name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: model
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Log in to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - 
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: slakter/hits-recsys
      - 
        name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            MODEL_PATH='./models/collab'
            MODEL_TYPE=collab